### ISSUE TITLE
Blue and Green Enchanted leaves don't work with passable leaves mods

### ISSUE THREAD

**Issue by K0-RR** [CorgiTaco/BYG#137]
When using mods that make leaves passable blue and green enchanted leaves glitch out and don't let me see through them. Below are links to screenshots showing this behavior and what is expected.
https://ibb.co/ZH0hVjg
https://ibb.co/r76mx8b
https://ibb.co/Fn4xt41

Passable leaves mod for fabric I'm using - 
https://www.curseforge.com/minecraft/mc-mods/tinytweaks

When using [Passable leaves [Fabric]](https://www.curseforge.com/minecraft/mc-mods/fabric-passable-leaves) everything works great

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3090260

**Comment by K0-RR** [comment]
In this file - BYG 1.0.14 - the issue is still present and now enchanted leaves work kinda like x-ray too (see screenshot below)
https://ibb.co/JrGMMhf
