### ISSUE TITLE
[Bug]: Texture errors on all BYG plants

### ISSUE THREAD

**Issue by SirLagAlot31** [CorgiTaco/BYG#697]
### Minecraft Version

1.18.2

### BYG Versions

1.3.7

### Terrablender

1.1.0.77

### Mod Loader

Forge

### Mod Loader Version

39.0.19

### Bug Severity

Major

### What happened?

![Texture Errors](https://user-images.githubusercontent.com/102772718/161174049-8b0c97d3-7042-46e5-a7f4-a76f4decc44e.png)
This image shows that all plant type blocks from the mod don't render correctly. This applies to vines, saplings, bushes, lily pads, grass, flat grass and flowers. This does not apply to leave blocks however. I've put down some vanilla saplings as well as a few from the Biomes O'Plenty mod to show that the issue does not occur with plants from vanilla and other mods. I believe this could be an incompatibility issue with a certain mod. I initially suspected better leaves but it was ruled out when the issue persisted after I experimented disabling the mod/texture pack.

Secondary potential minor bug: It appears that the saplings from this mod won't grow naturally or when bonemealed. I remembered this issue while setting up the image above when I came to planting the vanilla plants and Biomes O'Plenty ones, who grew in less than a few seconds (the tickspeed is set to 1000+). I was forced to cover those trees with string to stop them from growing while the ones from the BYG mod didn't grow at all, even when they were bonemealed.

### latest.log

[2022-01-14-1.log.gz](https://github.com/AOCAWOL/BYG/files/8393852/2022-01-14-1.log.gz)

**Comment by CorgiTaco** [comment]
Please use the latest version of byg as it is already fixed.

1.18.1: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3669462

1.18.2: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3712165

**Comment by SirLagAlot31** [comment]
Hi, I just updated the mod and this has solved the main issue, but I still don't understand what the correct conditions for growing these saplings are. From the looks of things, it seems that the trees will grow naturally after a while but aren't affected by bonemeal. If you could provide some insight that would be very helpful. Thanks

**Comment by CorgiTaco** [comment]
@SirLagAlot31 in 1.18.1 look in the `sapling-patterns` config, in 1.18.2 hold shift on any of our saplings in the inventory and itll display it

**Comment by SirLagAlot31** [comment]
Ok thank you for your help
